### ISSUE TITLE
plot_gene for marker genes, return multiple ggplot objects, how to show them in one picture

### ISSUE THREAD

**Issue by wubaosheng** [welch-lab/pyliger#2]
PRF1 = pyliger.plot_gene(ifnb_liger, "ABCA1", axis_labels = ['UMAP 1', 'UMAP 2'], return_plots = True)
# for x in PRF1.values():
#     x.draw(show=True)
print(PRF1)
PRF1['human'].draw(show=True)
![image](https://user-images.githubusercontent.com/50618480/159104466-bb4f7dc4-f76e-48a9-98cc-4167999ddcb1.png)

**Comment by Lulu0015** [comment]
Hi Baosheng, 

Currently, we can’t visualize all ggplot objects in one plot using plotnine (ggplot2 in python). The reason is that plotnine uses Matplotlib which doesn’t have a good layout manager to support subplotting. The simplest way to visualize all plots is to save them and examine them individually. You can combine them the way you like and you may refer to this code for saving one ggplot object. Please make sure you do this for all ggplot objects.

gene_plots[idx].save(filename = file_name, height=10, width=10, units = 'in', dpi=500, verbose=False)

Thanks,
Lu Lu

**Comment by wubaosheng** [comment]
thanks
